# Generated by Django 3.0.2 on 2020-02-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aidants_connect_web", "0012_organisations"),
    ]

    operations = [
        migrations.RenameField(model_name="usager", old_name="sub", new_name="sub_fc",),
        migrations.AddField(
            model_name="usager", name="sub_fi", field=models.TextField(blank=True),
        ),
    ]
